# Generated by Django 5.1.2 on 2024-11-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='categoria',
            new_name='servicio',
        ),
    ]
