# Generated by Django 5.1.2 on 2024-11-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_asignado_a_alter_ticket_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.type', verbose_name='Servicio'),
        ),
    ]
